apiVersion: v1
appVersion: "1.0"
description: A IdentityServer4 based OAuth / OpenId Connect server
home: https://www.outsurance.co.za
icon: https://www.outsurance.co.za/favicon.ico
keywords:
- identityserver4
- oauth
- oidc
maintainers:
- email: vanderbergg@out.co.za
  name: gvanderberg
name: identitysrv
version: 0.1.0
