apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "titansoft-xero-api.fullname" . }}-config
  labels:
    app: {{ template "titansoft-xero-api.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  cacheConnection: {{ .Values.configMap.cacheConnection | quote }}
  cachePassword: {{ .Values.configMap.cachePassword | quote }}
  environmentName: {{ .Values.configMap.environmentName | quote }}
  eventBusConnection: {{ .Values.configMap.eventBusConnection | quote }}
  eventBusPassword: {{ .Values.configMap.eventBusPassword | quote }}
  eventBusUserName: {{ .Values.configMap.eventBusUserName | quote }}
  identityUrl: {{ .Values.configMap.identityUrl | quote }}
  identityUrlHC: {{ .Values.configMap.identityUrlHC | quote }}
  instrumentationKey: {{ .Values.configMap.instrumentationKey | quote }}
  pathBase: {{ .Values.configMap.pathBase | quote }}
  sentryDsn: {{ .Values.configMap.sentryDsn | quote }}
  seqServerUrl: {{ .Values.configMap.seqServerUrl | quote }}
  xeroApi__AppType: {{ .Values.configMap.xeroApi__AppType | quote }}
  xeroApi__CallbackUrl: {{ .Values.configMap.xeroApi__CallbackUrl | quote }}
  xeroApi__ConsumerKey: {{ .Values.configMap.xeroApi__ConsumerKey | quote }}
  xeroApi__ConsumerSecret: {{ .Values.configMap.xeroApi__ConsumerSecret | quote }}
  xeroDatabase: {{ .Values.configMap.xeroDatabase | quote }}
  