apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "titansoft-xero-api.fullname" . }}-config
  labels:
    app: {{ template "titansoft-xero-api.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  environmentName: {{ .Values.configMap.environmentName | quote }}
  instrumentationKey: {{ .Values.configMap.instrumentationKey | quote }}
  connectionString: {{ .Values.configMap.connectionString | quote }}
  leadsApiUrl: http://localhost:4001
  schedulerApiUrl: http://localhost:4001
  schedulerWebUrl: http://localhost:4002
  serilogServerUrl: {{ .Values.configMap.serilogServerUrl | quote }}