apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "titansoft-xero-api.fullname" . }}-config
  labels:
    app: {{ template "titansoft-xero-api.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  environmentName: {{ .Values.configMap.environmentName | quote }}
  instrumentationKey: {{ .Values.configMap.instrumentationKey | quote }}
  connectionString: {{ .Values.configMap.connectionString | quote }}
  cacheConnection: {{ .Values.configMap.cacheConnection | quote }}
  eventBusConnection: {{ .Values.configMap.eventBusConnection | quote }}
  identityUrl: {{ .Values.configMap.identityUrl | quote }}
  identityUrlHC: {{ .Values.configMap.identityUrlHC | quote }}
  pathBase: {{ .Values.configMap.pathBase | quote }}
  seqServerUrl: {{ .Values.configMap.seqServerUrl | quote }}
  xeroAppType: {{ .Values.configMap.xeroAppType | quote }}
  xeroCallbackUrl: {{ .Values.configMap.xeroCallbackUrl | quote }}
  xeroConsumerKey: {{ .Values.configMap.xeroConsumerKey | quote }}
  xeroConsumerSecret: {{ .Values.configMap.xeroConsumerSecret | quote }}