apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "titansoft-xeroapp-web.fullname" . }}-config
  labels:
    app: {{ template "titansoft-xeroapp-web.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  environmentName: {{ .Values.configMap.environmentName | quote }}
  instrumentationKey: {{ .Values.configMap.instrumentationKey | quote }}
  pathBase: {{ .Values.configMap.pathBase | quote }}
  sentryDsn: {{ .Values.configMap.sentryDsn | quote }}
  seqServerUrl: {{ .Values.configMap.seqServerUrl | quote }}
  shopifyDatabase: {{ .Values.configMap.shopifyDatabase | quote }}