apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "identitysrv.fullname" . }}-config
  labels:
    app: {{ template "identitysrv.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ASPNETCORE_ENVIRONMENT: Development
  InstrumentationKey: 
  ConnectionString: Server=mssql;Database=IdentityDb;User Id=sa;Password=P@ssword;MultipleActiveResultSets=true;
  SerilogUrl: http://seq.monitoring
  LeadsApiUrl: 
  SchedulerApiUrl: 
  SchedulerWebUrl: 