apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "identitysrv.fullname" . }}-config
  labels:
    app: {{ template "identitysrv.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  Environment: {{ .Values.appSettings.environment | quote }}
  InstrumentationKey: {{ .Values.appSettings.instrumentationKey | quote }}
  ConnectionString: {{ .Values.appSettings.connectionString | quote }}
  LeadsApiUrl: http://localhost:4001
  SchedulerApiUrl: http://localhost:4001
  SchedulerWebUrl: http://localhost:4002
  SerilogServerUrl: {{ .Values.appSettings.serilogServerUrl | quote }}