apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "identity-srv.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "identity-srv.name" . }}
    helm.sh/chart: {{ include "identity-srv.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "identity-srv.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "identity-srv.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{- include "identity-srv.imagePullSecrets" . | indent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "identity-srv.fullname" . }}-config
                  key: environmentName
            - name: PATH_BASE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "identity-srv.fullname" . }}-config
                  key: pathBase
            - name: CacheConnection
              valueFrom:
                configMapKeyRef:
                  name: {{ template "identity-srv.fullname" . }}-config
                  key: cacheConnection
            - name: CachePassword
              valueFrom:
                configMapKeyRef:
                  name: {{ template "identity-srv.fullname" . }}-config
                  key: cachePassword
            - name: EventBusConnection
              valueFrom:
                configMapKeyRef:
                  name: {{ template "identity-srv.fullname" . }}-config
                  key: eventBusConnection
            - name: EventBusUserName
              valueFrom:
                configMapKeyRef:
                  name: {{ template "identity-srv.fullname" . }}-config
                  key: eventBusUserName
            - name: EventBusPassword
              valueFrom:
                configMapKeyRef:
                  name: {{ template "identity-srv.fullname" . }}-config
                  key: eventBusPassword
            - name: LeadsApiUrl
              valueFrom:
                configMapKeyRef:
                  name: {{ template "identity-srv.fullname" . }}-config
                  key: leadsApiUrl
            - name: ApplicationInsights__InstrumentationKey
              valueFrom:
                configMapKeyRef:
                  name: {{ template "identity-srv.fullname" . }}-config
                  key: instrumentationKey
            - name: ConnectionStrings__IdentityDatabase
              valueFrom:
                configMapKeyRef:
                  name: {{ template "identity-srv.fullname" . }}-config
                  key: connectionString
            - name: Serilog__WriteTo__1__Args__serverUrl
              valueFrom:
                configMapKeyRef:
                  name: {{ template "identity-srv.fullname" . }}-config
                  key: seqServerUrl
            - name: IsClusterEnv
              value: "True"
            - name: OrchestratorType
              value: "K8S"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
