apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "titansoft-identity-web.fullname" . }}-config
  labels:
    app: {{ template "titansoft-identity-web.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  connectionString: {{ .Values.configMap.connectionString | quote }}
  environmentName: {{ .Values.configMap.environmentName | quote }}
  identityDatabase: {{ .Values.configMap.identityDatabase | quote }}
  instrumentationKey: {{ .Values.configMap.instrumentationKey | quote }}
  pathBase: {{ .Values.configMap.pathBase | quote }}
  seqServerUrl: {{ .Values.configMap.seqServerUrl | quote }}