apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "titansoft-identity-svc.fullname" . }}-config
  labels:
    app: {{ template "titansoft-identity-svc.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  environmentName: {{ .Values.configMap.environmentName | quote }}
  instrumentationKey: {{ .Values.configMap.instrumentationKey | quote }}
  connectionString: {{ .Values.configMap.connectionString | quote }}
  shopifyApiUrl: {{ .Values.configMap.shopifyApiUrl | quote }}
  shopifyWebUrl: {{ .Values.configMap.shopifyWebUrl | quote }}
  xeroApiUrl: {{ .Values.configMap.xeroApiUrl | quote }}
  pathBase: {{ .Values.configMap.pathBase | quote }}
  seqServerUrl: {{ .Values.configMap.seqServerUrl | quote }}