apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "titansoft-shopify-web.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "titansoft-shopify-web.name" . }}
    helm.sh/chart: {{ include "titansoft-shopify-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "titansoft-shopify-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "titansoft-shopify-web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{- include "titansoft-shopify-web.imagePullSecrets" . | indent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: environmentName
            - name: PATH_BASE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: pathBase
            - name: CacheConnection
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: cacheConnection
            - name: CachePassword
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: cachePassword
            - name: CallBackUrl
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: callBackUrl
            - name: IdentityUrl
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: identityUrl
            - name: IdentityUrlHC
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: identityUrlHC
            - name: ShopifyUrl
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: shopifyUrl
            - name: ShopifyUrlHC
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: shopifyUrlHC
            - name: XeroUrl
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: xeroUrl
            - name: XeroUrlHC
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: xeroUrlHC
            - name: ApplicationInsights__InstrumentationKey
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: instrumentationKey
            - name: Sentry__Dsn
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: sentryDsn
            - name: Serilog__WriteTo__1__Args__dsn
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: sentryDsn
            - name: Serilog__WriteTo__2__Args__serverUrl
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: seqServerUrl
            - name: Serilog__Properties__Environment
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: environmentName
            - name: shopifyApi__AppHost
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: shopifyApi__AppHost
            - name: ShopifyApi__ConsumerKey
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: shopifyApi__ConsumerKey
            - name: ShopifyApi__ConsumerSecret
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: shopifyApi__ConsumerSecret
            - name: XeroApi__AppType
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: xeroApi__AppType
            - name: XeroApi__CallbackUrl
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: xeroApi__CallbackUrl
            - name: XeroApi__ConsumerKey
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: xeroApi__ConsumerKey
            - name: XeroApi__ConsumerSecret
              valueFrom:
                configMapKeyRef:
                  name: {{ template "titansoft-shopify-web.fullname" . }}-config
                  key: xeroApi__ConsumerSecret
            - name: IsClusterEnv
              value: "True"
            - name: OrchestratorType
              value: "K8S"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
